name: Monthly Insider Run

on:
  schedule:
    - cron: '0 6 2 * *'   # Runs 2nd of every month
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python insider_pipeline.py
        env:
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
         EMAIL: ${{ secrets.EMAIL }}
         GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
